// Code generated by "stringer -type=ReadyState"; DO NOT EDIT.

package sse

import "strconv"

const _ReadyState_name = "ConnectingOpenClosingClosed"

var _ReadyState_index = [...]uint8{0, 10, 14, 21, 27}

func (i ReadyState) String() string {
	if i >= ReadyState(len(_ReadyState_index)-1) {
		return "ReadyState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ReadyState_name[_ReadyState_index[i]:_ReadyState_index[i+1]]
}
